### PR TITLE
Use ActiveRecord for session store

### LINKED ISSUE #2236: enable activerecord-session_store
We had this in mongo and we should do it in pg too -- https://github.com/rails/activerecord-session_store

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

easy peasy one - we do our session store in database. Currently mongo; this swaps it to activerecord/pg.

This pull request makes the following changes:
* set up our session store in activerecord rather than mongo

It relates to the following issue #s: 
* Fixes #2236

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

**Review by lomky — APPROVED** [review]
LGTM! 🎉 🖇️

**Review by lomky — CHANGES_REQUESTED** [review]
Just kidding! can you submit the Gemfile.lock that has the mongo gem removed? my local dev sees changes

**Comment by colinxfleming** [comment]
lol whoops

**Comment by lomky** [comment]
loooool

**Pull request merged**
