### PR TITLE
Deknapsack

### LINKED ISSUE #1177: What's the knapsack gem's problem?
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Run tests in CI efficiently by splitting our tests onto parallel boxes in Circle. This used to be okay via something and then they started recommending the knapsack gem, but now THAT is causing some sketchy segfaults.

* **What feature or behavior is this required for?**
Running CI tests efficiently (meaningful, since we deploy to sandbox via CI)

* **How could we solve this issue? (Not knowing is okay!)**
Investigate the segfaults and come up with a solution that lets us continue splitting the test suite among boxes. Even is nice but not necessary. 

* **Anything else?**
nope!

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

Goal here is to get rid of knapsack and move back to regular parallelization without a sub-library, which I loathe.

Expect lots of back and forth and commits to circle.yml.

This pull request makes the following changes:
* smell ya later knapsack

It relates to the following issue #s: 
* Fixes #1177

### CODE REVIEW

**Comment by colinxfleming** [comment]
This seems to work, other than a failing test related to either upgrading to 5.1, or to something totally stupid like using `rails test` instead of `rake test`. @DarthHater other than the test failure, does this look okay to you?

**Comment by DarthHater** [comment]
Have we tried raising this with knapsack and going hey why isn't this working? We could maybe do that to see if it's something easy.

**Comment by colinxfleming** [comment]
tbh I was never wild about knapsack and threw it in because I was not willing to accept 6m builds, so I'm kind of inclined to take this opportunity to ditch it! This also lets us restore bubbling errors to the top with some junit xml noise, which knapsack didn't play nice with.

**Comment by colinxfleming** [comment]
hm, looks like a host of other integration tests are also choking because of API changes. Wonder if this is fixable with systemtests?

**Comment by colinxfleming** [comment]
well, that's most of em, anyway. remaining test failing in test/integration/user_management_test.rb:88. I'll deal with it later.

**Comment by colinxfleming** [comment]
Had a hunch that a lonely operator / try would handle this and it seems to be right! Seeing if this passes CI.

**Comment by colinxfleming** [comment]
boom. @DarthHater let me know if you want any changes, but this is all passing and we should be good to merge it into the 5.1 branch.

**Comment by colinxfleming** [comment]
after, of course, our good for nothing CI build passes.

**Pull request merged**
