### PR TITLE
Add ability to edit practical support forms

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

Not shipping because there's some additional UI to do, but this sets up update and destroy in the UI. Still not quite primetime ready but materially closer.

This pull request makes the following changes:
* Sets up entry update and destroy (no tests yet)
* some UI cleanup and breaking things into more rest-y routes
* turn on the autosave!

The state of the world:

image

Still todo are tests and localization and exports at least, and doing a quick UI check with @mlindberg61 .

It relates to the following issue #s: 
* Bumps #1493

### CODE REVIEW

**Comment by mlindberg9** [comment]
Let's have @harumhelmy take lead with the UI test -- I think it's up to her if I should weigh in.

**Comment by harumhelmy** [comment]
You should feel free to if you have capacity, Marie. I haven't been to Code
for DC for the last couple of meetups, but will plan on going to the next
one!

*Harum Helmy*
(ha-room hell-me)
Pronouns <https://www.mypronouns.org/what-and-why/>: she & they

**Comment by mlindberg9** [comment]
Upon spot check, it looks great. I think this is an important symbolic and logistical step for where we want case management to be going. Let me know if you have a beta version that I can click through to, but not necessary. Can we add a link for more info without too much consequence?

**Comment by colinxfleming** [comment]
@mlindberg9 yeah, it's shaping up pretty nicely (s/o to @harumhelmy who did the bulk of the heavy lifting on it). I think that since you've been quarterbacking a lot of this lately your input is really valuable here, so if you expect any rough edges

Can you give me some sense of where you want the link to go or do? Is that a practical support doc or something like that? We can probably accommodate, just need to know what you have in mind here. The next code for dc mtg is June 26 if you'd prefer to talk shop in person.

I can deploy a version of this for you to poke at this weekend.

**Comment by mlindberg9** [comment]
@colinxfleming Yes. I am thinking about a practical support document -- right now I have this in mind. https://docs.google.com/document/d/16R1FZMqJA3i_4uZh49Ud5ULsLiH3cr6qKPpJrLuvt1E/edit?usp=sharing

**Pull request merged**
