### PR TITLE
Change onlinefaxes.com to www.efax.com

### LINKED ISSUE #1295: Change Name of Fax Service
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
onlinefaxes.com is now www.efax.com. We should change all the references in DARIA to reflect this.

* **What feature or behavior is this required for?**
Direct access for the fax service.
* **How could we solve this issue? (Not knowing is okay!)**
Change the labels and links.
* **Anything else?**
DARIA is awesome!

### PR DESCRIPTION
**Pull request by mdworken**
I rule and have completed some work on Case Manager that's ready for review!

This pull request makes the following changes:
references to onlinefaxes.com are now to www.efax.com

It relates to the following issue #s: 
* Fixes #1295

### CODE REVIEW

**Comment by mdworken** [comment]
Can someone merge this in when they get the chance?

**Comment by colinxfleming** [comment]
hey @mdworken would you mind reopening this so I can merge?

**Comment by mdworken** [comment]
Sorry, I made a git mistake and some additional changes were pushed to this that shouldn't be approved, so make sure nothing after 17ca5a1 goes through.

**Comment by colinxfleming** [comment]
thanks @mdworken !

**Pull request merged**
