### PR TITLE
Replaced remaining instances of bootstrap_form_for with bootstrap_form_with

### LINKED ISSUE #1861: Replace bootstrap_form_for with bootstrap_form_with
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Rails used to do forms that were backed by models with `form_for obj` and forms that just hit a URL with `form_tag url`. Around 5.1 they introduced `form_with`, which took a keyword argument `url` or `model` and could do either. (We generally use `bootstrap_form_for`, which is basically just a little bit of extra styling but is pretty much the same as `form_for`.

A primer on `form_with`: https://m.patrikonrails.com/rails-5-1s-form-with-vs-old-form-helpers-3a5f72a8c78a

We have several instances of `bootstrap_form_for` that I would like to convert to `bootstrap_form_with`:

```
Colins-Air:dcaf_case_management colin$ git grep bootstrap_form_with
app/views/accountants/_search_form.html.erb:  <%= bootstrap_form_with url: 'accountant/search', remote: true, layout: :inline do |f| %>
app/views/clinicfinders/_search_form.html.erb:    <%= bootstrap_form_with url: clinicfinder_search_path,
app/views/clinics/_clinic_form.html.erb:<%= bootstrap_form_with model: @clinic, local: true do |f| %>
app/views/configs/_config.html.erb:    <%= bootstrap_form_with model: config, inline: true do |f| %>
app/views/dashboards/_search_form.html.erb:  <%= bootstrap_form_with url: '/search', layout: :inline do |p| %>
app/views/devise/sessions/new.html.erb:      <%= bootstrap_form_with model: resource, as: resource_name, url: session_path(resource_name), local: true do |f| %>
app/views/lines/new.html.erb:    <%= bootstrap_form_with url: lines_path, local: true, class: 'line-select-form' do |f| %>
app/views/patients/_abortion_information.html.erb:  <%= bootstrap_form_with model: patient,
app/views/patients/_abortion_information.html.erb:  <%= bootstrap_form_with model: patient,
app/views/patients/_fulfillment.html.erb:  <%= bootstrap_form_with model: patient,
app/views/patients/_new_patient.html.erb:<%= bootstrap_form_with model: patient do |f| %>
app/views/patients/_notes.html.erb:  <%= bootstrap_form_with model: [patient, note],
app/views/patients/_patient_information.html.erb:  <%= bootstrap_form_with model: patient,
app/views/patients/_pledge.html.erb:          <%= bootstrap_form_with url: generate_pledge_patient_path(patient),
app/views/patients/_pledge.html.erb:      <%= bootstrap_form_with model: @patient,
app/views/patients/data_entry.html.erb:<%= bootstrap_form_with model: @patient,
app/views/users/_search_form.html.erb:<%= bootstrap_form_with url: users_search_path,
app/views/users/edit.html.erb:    <%= bootstrap_form_with model: @user do |f| %>
```

We've done all the URL ones, but there are a bunch of model ones still in the codebase; this is to get them out.

* **What feature or behavior is this required for?**

Easy rails upgrades!

* **How could we solve this issue? (Not knowing is okay!)**

* go thru the list of bootstrap_form_for and change them to `bootstrap_form_with model: patient`  (or whatever the model object is).
* `bootstrap_form_with` is `remote: true` by default, so for any that ARE NOT `remote: true`, make sure you add `local: true` to the options hash.
* confirm that tests still pass

* **Anything else?**

There are a few tricky ones in there - I don't know how `bootstrap_form_with` will handle nested models like `[patient, new_external_pledge]` such as in app/views/external_pledges/_new.html.erb. Please feel free to ask for help if that is not a free basket!

### PR DESCRIPTION
**Pull request by harumhelmy**
I rule and have completed some work on Case Manager that's ready for review!

I changed remaining instances of bootstrap_form_for in the codebase to bootstrap_form_with, and confirmed that all tests are still passing! Went a bit overboard with separating the commits, heh. 

It relates to the following issue #s: 
* Fixes #1861

### CODE REVIEW

**Comment by colinxfleming** [comment]
this looks right to me, so I'm surprised the tests aren't passing. @harumhelmy this might be a good learning exercise, let's talk about this offthread.

**Comment by harumhelmy** [comment]
Hmm, all tests are passing on my end, actually. (Except for audit_trail_test but I checked with Kevin and he said that one seems to always fail on local builds?)

**Comment by colinxfleming** [comment]
@harumhelmy - here are the problematic three. they're all system tests, so kinda slow:

```
Failure:
UpdatePatientInfoTest::changing abortion information#test_0002_should alter the abortion information [/home/circleci/abortioneering/test/system/update_patient_info_test.rb:166]:
Expected false to be truthy.


rails test test/system/update_patient_info_test.rb:155


Failure:
SubmitPledgeTest::submitting a pledge#test_0001_should let you mark a pledge submitted [/home/circleci/abortioneering/test/system/submit_pledge_test.rb:50]:
Expected false to be truthy.


rails test test/system/submit_pledge_test.rb:29

Failure:
ActivityLogTest::logging a pledge#test_0001_should log a pledge into the activity log [/home/circleci/abortioneering/test/system/activity_log_test.rb:53]:
Expected false to be truthy.


rails test test/system/activity_log_test.rb:40
```

probably these all have straightforward fixes (or might be just our codebase showing its age a little bit, ha). are you set up to run systemtests?

**Comment by harumhelmy** [comment]
Ooh, I've never run system tests before! Just looked it up and seeing the failures you shared. Will look into them and connect with you offthread if I can't figure it out. Thanks @colinxfleming!

**Comment by colinxfleming** [comment]
worse comes to worse, system tests have a syntax that optimizes for readability, so you can probably recreate them from those steps and diagnose problems from there.

**Comment by harumhelmy** [comment]
I just needed to run `rails test:system` to run system tests. Turns out you have to explicitly add the HTML class "edit_[modelname]" to the bootstrap_form_with options hash. The three system tests you mention are now passing on my end, @colinxfleming!

**Pull request merged**
