### PR TITLE
New checkbox field for ultrasound info

### PR DESCRIPTION
**Pull request by nikobozi**
This pull request relates to #1497 
- New field `completed_ultrasound` added to patient, as well as the checkbox view and helper text
- updated existing system test case

**Changes in views**  
Now there is a new checkbox for the ultrasound info available. How to see it: 
- click on a patient
- click on Abortion Information tab  
new_field

### CODE REVIEW

**Comment by colinxfleming** [comment]
thanks @nicobozi, and welcome to the project! 

I'm a little tied up for the next day or two but promise I will review this shortly.

**Comment by nikobozi** [comment]
@colinxfleming thank you for the feedback! I've updated the PR with your suggestions and edited the initial PR message to reflect those changes

**Comment by colinxfleming** [comment]
a beaut, thank you @nikobozi !

**Comment by colinxfleming** [comment]
CI failing because of known CircleCI bug on forks; merging

**Pull request merged**
