### PR TITLE
Fixes issue #1053 remove zip code field

### LINKED ISSUE #1053: Remove zip code
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
We don't really need to track zip code in this app, so let's take it out.

* **What feature or behavior is this required for?**
Patient information security, not keeping extra stuff around.

* **How could we solve this issue? (Not knowing is okay!)**
Remove the field from the model in `app/models/patient.rb`!

* **Anything else?**
See discussion in #306

### PR DESCRIPTION
**Pull request by itroman**
I rule and have completed some work on Case Manager that's ready for review!

Fixes issue #1053 remove zip code field

This pull request makes the following changes:
* Remove the field from the model in `app/models/patient.rb!`

It relates to the following issue #s: 
* Fixes #1053

### CODE REVIEW

**Comment by colinxfleming** [comment]
Looking good @itroman , thanks for the quick turnaround on this!

No good deed goes unpunished, though -- It looks like our test suite is failing, and that we need to remove ZIP from a few other places. I would guess we'll need to do it in the following places:

* `app/views/patients/_patient_information.html.erb` (the form field)
* `app/views/patients/data_entry.html.erb` (form field)
* `test/integration/update_patient_information_test.rb` (two spots, the `fill_in` and the `assert`)
* `test/integration/data_entry_test.rb` (two spots, the `fill_in` and the `assert`)

After those changes, you can run `rake test` in a terminal to run the test suite. If it comes back green, we're good -- if it comes back red, we might have a little more debugging to do, but it should spit out some helpful messages.

Sorry this turned out to be a little more complicated than I thought!

(PS if you get a chance please pop into our slack channel! Link in the readme.)

**Comment by itroman** [comment]
Alrighty!  I'll get goin on this.

**Comment by itroman** [comment]
Made additional changes to:

- `app/views/patients/_patient_information.html.erb`
- `test/integration/update_patient_info_test.rb`

Test results were:  `366 tests, 783 assertions, 0 failures, 0 errors, 0 skips`

so hopefully that should do it.

**Comment by colinxfleming** [comment]
Looking good, my dude! Thanks for digging in and turning these changes around so quick. Merging now, and this will go into prod on Sunday. 

How'd you find us, if you don't mind my asking?

**Comment by colinxfleming** [comment]
(ps welcome aboard!  💯 🔥 🌻 )

**Pull request merged**
