### PR TITLE
Rip out Gemnasium

### PR DESCRIPTION
**Pull request by DarthHater**
I rule and have completed some work on Case Manager that's ready for review!

Removes Gemnasium:

https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/

This pull request makes the following changes:
* Removes badge
* Removes docs related to gemnasium

### CODE REVIEW

**Comment by colinxfleming** [comment]
RIP Gemnasium

Is there something we can sub in here? Maybe the in house github option or something? We get a layer of safety from `bundle-audit` and `ruby_audit` but it's a nice early warning system generally.

**Comment by DarthHater** [comment]
GitHub just shows up in the ui now if you go into settings or whatever.
Kinda the same deal as gemnasium but since only contributors have access I
wasn’t going to add it to the readme.

**Comment by colinxfleming** [comment]
If it's cool with you I'm going to keep this trucking for a little while because gemnasium seems to have a yellow status for when something isn't alerting, but is still out of date, which github doesn't have. Also I'm sad we never got to hit the auto update :(

**Comment by colinxfleming** [comment]
D:

**Pull request merged**
