### PR TITLE
PG: Substitute PaperTrail in for mongo AuditTrail

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

We start here by subbing in PaperTrail, the versioning system, for Mongo's AuditTrail.

Tests require a few dependent objects (user and patient specifically) so I did not turn on the tests, but this is as good a place to start as any.

I don't think there's a good way to try this out or otherwise test drive it, so I would recommend reviewing just by looking at the code.

This pull request makes the following changes:
* Remove mongo AuditTrail
* Integrate PaperTrail in as much as we can without having papertrailable stuff yet

no view change

It relates to the following issue #s: 
* Bumps #2072 

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

**Comment by lomky** [comment]
Some `history_tracks` slipped through! Mostly in tests, but also in the `urgency` concern where it redefines `recent_history_tracks`

```bash
Mon Mar 08 17:27:33 [pg-papertrail] ~/repos/dcaf $ gg "\<history_tracks\>"
app/models/concerns/history_trackable.rb:# Methods pertaining to parsing history_tracks
app/models/concerns/urgency.rb:    history_tracks.select { |ht| ht.updated_at > 6.days.ago }
test/controllers/external_pledges_controller_test.rb:      assert_equal @pledge.history_tracks.count, 2
test/controllers/external_pledges_controller_test.rb:      last_changes = @pledge.history_tracks.last
test/controllers/external_pledges_controller_test.rb:                                     .history_tracks.count' do
test/controllers/practical_supports_controller_test.rb:                                       .history_tracks.count' do
test/helpers/change_log_helper_test.rb:      @changeset = pt.history_tracks.last
test/models/call_test.rb:      assert @call.respond_to? :history_tracks
test/models/call_test.rb:      assert @call.history_tracks.count > 0
test/models/clinic_test.rb:      assert @clinic.respond_to? :history_tracks
test/models/clinic_test.rb:      assert @clinic.history_tracks.count > 0
test/models/external_pledge_test.rb:      assert @pledge.respond_to? :history_tracks
test/models/external_pledge_test.rb:      assert @pledge.history_tracks.count > 0
test/models/fulfillment_test.rb:      assert @fulfillment.respond_to? :history_tracks
test/models/fulfillment_test.rb:      assert @fulfillment.history_tracks.count > 0
test/models/note_test.rb:      assert @note.respond_to? :history_tracks
test/models/note_test.rb:      assert @note.history_tracks.count > 0
test/models/patient_test.rb:      assert @patient.respond_to? :history_tracks
test/models/patient_test.rb:      assert @patient.history_tracks.count > 0
test/models/practical_support_test.rb:      assert @psupport1.respond_to? :history_tracks
test/models/practical_support_test.rb:      assert @psupport1.history_tracks.count > 0
```

**Comment by colinxfleming** [comment]
I wouldn't worry about those as much - the tests still use `history_tracks` since they're all on mongo, and I'll do the `Urgency` concern when we get to the Patient model (the only component that uses it). Changing them would widen the scope a bit.

**Comment by xmunoz** [comment]
Not sure if this is related to the comment above, but the local developer environment no longer builds on this PR.

```
docker-compose run --rm web rails db:create db:migrate db:seed
...
== 20201212010730 CreateEvents: migrating =====================================
-- create_table(:events)
   -> 0.0042s
-- add_index(:events, :created_at)
   -> 0.0034s
-- add_index(:events, :line)
   -> 0.0028s
== 20201212010730 CreateEvents: migrated (0.0105s) ============================

rails aborted!
NameError: uninitialized constant AuditTrail
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/inflector/methods.rb:282:in `const_get'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/inflector/methods.rb:282:in `block in constantize'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/inflector/methods.rb:280:in `each'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/inflector/methods.rb:280:in `inject'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/inflector/methods.rb:280:in `constantize'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/core_ext/string/inflections.rb:68:in `constantize'
/usr/local/bundle/gems/mongoid-history-0.8.3/lib/mongoid/history/trackable.rb:80:in `tracker_class'
/usr/local/bundle/gems/mongoid-history-0.8.3/lib/mongoid/history/trackable.rb:330:in `track_history_for_action'
/usr/local/bundle/gems/mongoid-history-0.8.3/lib/mongoid/history/trackable.rb:260:in `track_create'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:139:in `run_callbacks'
/usr/local/bundle/gems/mongoid-7.0.8/lib/mongoid/interceptable.rb:132:in `run_callbacks'
/usr/local/bundle/gems/mongoid-7.0.8/lib/mongoid/persistable/creatable.rb:119:in `block in prepare_insert'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/callbacks.rb:101:in `run_callbacks'
/usr/local/bundle/gems/mongoid-7.0.8/lib/mongoid/interceptable.rb:132:in `run_callbacks'
/usr/local/bundle/gems/mongoid-7.0.8/lib/mongoid/persistable/creatable.rb:118:in `prepare_insert'
/usr/local/bundle/gems/mongoid-7.0.8/lib/mongoid/persistable/creatable.rb:23:in `insert'
/usr/local/bundle/gems/mongoid-7.0.8/lib/mongoid/persistable/creatable.rb:180:in `block in create!'
/usr/local/bundle/gems/mongoid-7.0.8/lib/mongoid/threaded/lifecycle.rb:161:in `_creating'
/usr/local/bundle/gems/mongoid-7.0.8/lib/mongoid/persistable/creatable.rb:175:in `create!'
/usr/src/app/db/seeds.rb:17:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/engine.rb:557:in `block in load_seed'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/engine.rb:675:in `with_inline_jobs'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/engine.rb:557:in `load_seed'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/tasks/database_tasks.rb:440:in `load_seed'
/usr/local/bundle/gems/activerecord-6.0.3.5/lib/active_record/railties/databases.rake:331:in `block (2 levels) in <main>'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.0.3.5/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

**Review by xmunoz — COMMENTED** [review]
See above

**Comment by colinxfleming** [comment]
hm looks like AuditTrail is still being quietly invoked when a User is created? I'll take a look

**Comment by colinxfleming** [comment]
actually, probably easier to just restore AuditTrail and the associated test for now, since they're still part of the MongoVerse at this point.

**Comment by colinxfleming** [comment]
bleh that just causes a different issue. I think the root problem here is that audit trail is pretty deeply nested. We can approach this one of two ways:
* accept that it's just something ugly we have to get out of the way and review the code, but not fret that we can't spin up a dev environment yet OR
* do it last after the models are resorted
do you have an opinion/preference @xmunoz ?

**Comment by xmunoz** [comment]
Since you @colinxfleming are largely going to be working on this, I think the decision is up to you. If I were doing it though, I'm not sure how I would be able to convert the other models without a working dev environment, so I would probably opt for option 2. But again, this is your feature branch, so I encourage you to do whatever is easier for you to work with.

**Comment by colinxfleming** [comment]
per @xmunoz 's very good critique in here, I've adjusted the approach a bit and will keep this consistent for all of the chunks of this where possible --

* rails db:drop db:create db:migrate db:seed should work
* rails test should work (though, not necessarily pass)
* rails s should spin up a server
* the call list dashboard and patient edit view should both work

**Review by lomky — APPROVED** [review]
LGTM! 🎉 And the standard you set passes for me locally.

**Comment by colinxfleming** [comment]
thank you @lomky !

**Pull request merged**
