### PR TITLE
Update nokogiri to squash a vulnerability

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

Are the legends true? pre-compiled nokogiri is here????

(Also squashes a vuln, I believe.)

This pull request makes the following changes:
* bundle update nokogiri

no view changes

no issues

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

**Comment by xmunoz** [comment]
I don't believe we are affected by this vulnerability: https://github.com/sparklemotion/nokogiri/security/advisories/GHSA-vr8q-g5c7-m54m

That said, if you want upgrade nokogiri, please also update the Gemfile: https://github.com/DCAFEngineering/dcaf_case_management/blob/main/Gemfile#L8

**Review by xmunoz — COMMENTED** [review]
See above.

**Comment by colinxfleming** [comment]
this has started to fail builds - I'm going to bump the gemfile as suggested and then merge, I think.

**Comment by colinxfleming** [comment]
Gemfile bumped to match the lock - godmode merging.

**Pull request merged**
