### PR TITLE
Migrate Note to PG

### PR DESCRIPTION
**Pull request by colinxfleming**
I rule and have completed some work on Case Manager that's ready for review!

This is it! This is the one that lets us log in cleanly again. You can run `rails s` and log in, and do some basic call stuff like logging them, moving patients around in the call list, etc.

test the migration via:

```
git checkout main && rails db:drop db:create db:migrate db:seed
git checkout pg-note && rails db:migrate migrate_to_pg:clinic_user_patient
rails c
Note.count # 17
```

or, you could load up the main page I guess, and see the notes section in the call list.

This pull request makes the following changes:
* Port Note model to pg

no view changes

It relates to the following issue #s: 
* Bumps #2072 

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

**Comment by lomky** [comment]
my migrate fails! I tried it twice to the same result. It seems to be dying unable to find a patient?

migrate_to_pg erroring with missing patient

As ran: 
```
  516  git checkout main && rails db:drop db:create db:migrate db:seed
  517  git checkout pg-note
  518  rails db:migrate
  519  rails migrate_to_pg:clinic_user_patient

```

**Comment by colinxfleming** [comment]
okay, this is weird -- I've got that running clean with the following output - 

```
Colins-Air:dcaf_case_management colin$ rails migrate_to_pg:clinic_user_patient
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.1-compliant syntax, but you are running 2.7.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
4 Clinic migrated to pg
3 User migrated to pg
39 Patient migrated to pg
39 Fulfillment migrated to pg
141 calls migrated to pg
6 CallListEntry migrated to pg
17 notes migrated to pg
```

can you check that you're on the commit 13e3e545c6b462a839e4e99c19d29fc91bb1c2bd ?

**Comment by lomky** [comment]
I am!

```
Sat May 08 20:31:09 [pg-note] ~/repos/dcaf $ git log --oneline -1
13e3e545 (HEAD -> pg-note, origin/pg-note) squash migration problems

Sat May 08 20:31:25 [pg-note] ~/repos/dcaf $ git checkout main && rails db:drop db:create db:migrate db:seed
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.1-compliant syntax, but you are running 2.7.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Dropped database 'dcaf_case_management_development'
Dropped database 'dcaf_case_management_test'
Created database 'dcaf_case_management_development'
Created database 'dcaf_case_management_test'
== 20201119043849 InstallPgcrypto: migrating ==================================
-- enable_extension("pgcrypto")
   -> 0.0217s
== 20201119043849 InstallPgcrypto: migrated (0.0218s) =========================

== 20201120043849 CreateVersions: migrating ===================================
-- create_table(:versions)
   -> 0.0107s
-- add_index(:versions, [:item_type, :item_id])
   -> 0.0068s
== 20201120043849 CreateVersions: migrated (0.0177s) ==========================

== 20201207043840 CreateConfigs: migrating ====================================
-- create_table(:configs)
   -> 0.0129s
-- add_index(:configs, :config_key)
   -> 0.0055s
== 20201207043840 CreateConfigs: migrated (0.0186s) ===========================

== 20201212010730 CreateEvents: migrating =====================================
-- create_table(:events)
   -> 0.0143s
-- add_index(:events, :created_at)
   -> 0.0069s
-- add_index(:events, :line)
   -> 0.0057s
== 20201212010730 CreateEvents: migrated (0.0272s) ============================

Seed completed! Inserted 39 patient objects. 
Inserted 4 clinic objects. 
Inserted 3 user objects. 
Inserted 9 config objects. 
Inserted 158 event objects. 
User credentials are as follows: EMAIL: test@example.com PASSWORD: P4ssword

Sat May 08 20:31:42 [main] ~/repos/dcaf $ git checkout pg-note && rails db:migrate migrate_to_pg:clinic_user_patient
Switched to branch 'pg-note'
Your branch is up to date with 'origin/pg-note'.
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.1-compliant syntax, but you are running 2.7.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
== 20210307202735 CreateClinics: migrating ====================================
-- create_table(:clinics)
   -> 0.0458s
== 20210307202735 CreateClinics: migrated (0.0460s) ===========================

== 20210403213315 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0129s
== 20210403213315 CreateUsers: migrated (0.0130s) =============================

== 20210403213437 AddDeviseToUsers: migrating =================================
-- change_table(:users)
   -> 0.0142s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0076s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0061s
== 20210403213437 AddDeviseToUsers: migrated (0.0282s) ========================

== 20210410151149 CreatePatients: migrating ===================================
-- create_table(:patients)
   -> 0.0575s
-- add_index(:patients, :primary_phone, {:unique=>true})
   -> 0.0115s
-- add_index(:patients, :other_phone)
   -> 0.0091s
-- add_index(:patients, :other_contact)
   -> 0.0057s
-- add_index(:patients, :name)
   -> 0.0102s
-- add_index(:patients, :line)
   -> 0.0132s
-- add_index(:patients, :urgent_flag)
   -> 0.0094s
-- add_index(:patients, :identifier)
   -> 0.0097s
-- add_index(:patients, :pledge_sent)
   -> 0.0101s
== 20210410151149 CreatePatients: migrated (0.1375s) ==========================

== 20210415015227 CreateFulfillment: migrating ================================
-- create_table(:fulfillments)
   -> 0.0289s
-- add_index(:fulfillments, :fulfilled)
   -> 0.0090s
-- add_index(:fulfillments, :audited)
   -> 0.0083s
== 20210415015227 CreateFulfillment: migrated (0.0466s) =======================

== 20210426033002 CreateCalls: migrating ======================================
-- create_table(:calls)
   -> 0.0226s
== 20210426033002 CreateCalls: migrated (0.0227s) =============================

== 20210502050214 CreateCallListEntries: migrating ============================
-- create_table(:call_list_entries)
   -> 0.0271s
-- add_index(:call_list_entries, :line)
   -> 0.0052s
== 20210502050214 CreateCallListEntries: migrated (0.0324s) ===================

== 20210503043154 CreateNotes: migrating ======================================
-- create_table(:notes)
   -> 0.0247s
== 20210503043154 CreateNotes: migrated (0.0249s) =============================

4 Clinic migrated to pg
3 User migrated to pg
39 Patient migrated to pg
39 Fulfillment migrated to pg
141 calls migrated to pg
rails aborted!
ActiveRecord::RecordNotFound: Couldn't find Patient
/media/lomky/FreshStart2021/Documents/repos/dcaf/lib/tasks/migrate_to_pg.rake:103:in `block (4 levels) in <main>'
/media/lomky/FreshStart2021/Documents/repos/dcaf/lib/tasks/migrate_to_pg.rake:128:in `block in migrate_model'
/media/lomky/FreshStart2021/Documents/repos/dcaf/lib/tasks/migrate_to_pg.rake:124:in `migrate_model'
/media/lomky/FreshStart2021/Documents/repos/dcaf/lib/tasks/migrate_to_pg.rake:107:in `block (3 levels) in <main>'
/media/lomky/FreshStart2021/Documents/repos/dcaf/lib/tasks/migrate_to_pg.rake:33:in `block (2 levels) in <main>'
bin/rails:4:in `<main>'
Tasks: TOP => migrate_to_pg:clinic_user_patient
(See full trace by running task with --trace)

Sat May 08 20:31:56 [pg-note] ~/repos/dcaf $ 
```

**Comment by colinxfleming** [comment]
wut

**Comment by colinxfleming** [comment]
command for command it blends for me:
```
Colins-Air:dcaf_case_management colin$ git log --oneline -1
13e3e545 (HEAD -> pg-note, origin/pg-note) squash migration problems
Colins-Air:dcaf_case_management colin$ git checkout main && rails db:drop db:create db:migrate db:seed
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.1-compliant syntax, but you are running 2.7.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Dropped database 'dcaf_case_management_development'
Dropped database 'dcaf_case_management_test'
Created database 'dcaf_case_management_development'
Created database 'dcaf_case_management_test'
== 20201119043849 InstallPgcrypto: migrating ==================================
-- enable_extension("pgcrypto")
   -> 0.1704s
== 20201119043849 InstallPgcrypto: migrated (0.1705s) =========================

== 20201120043849 CreateVersions: migrating ===================================
-- create_table(:versions)
   -> 0.0346s
-- add_index(:versions, [:item_type, :item_id])
   -> 0.0060s
== 20201120043849 CreateVersions: migrated (0.0407s) ==========================

== 20201207043840 CreateConfigs: migrating ====================================
-- create_table(:configs)
   -> 0.0523s
-- add_index(:configs, :config_key)
   -> 0.0045s
== 20201207043840 CreateConfigs: migrated (0.0570s) ===========================

== 20201212010730 CreateEvents: migrating =====================================
-- create_table(:events)
   -> 0.0403s
-- add_index(:events, :created_at)
   -> 0.0069s
-- add_index(:events, :line)
   -> 0.0074s
== 20201212010730 CreateEvents: migrated (0.0558s) ============================

Seed completed! Inserted 39 patient objects. 
Inserted 4 clinic objects. 
Inserted 3 user objects. 
Inserted 9 config objects. 
Inserted 158 event objects. 
User credentials are as follows: EMAIL: test@example.com PASSWORD: P4ssword
Colins-Air:dcaf_case_management colin$ git checkout pg-note && rails db:migrate migrate_to_pg:clinic_user_patient
Switched to branch 'pg-note'
warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.1-compliant syntax, but you are running 2.7.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
== 20210307202735 CreateClinics: migrating ====================================
-- create_table(:clinics)
   -> 0.0401s
== 20210307202735 CreateClinics: migrated (0.0402s) ===========================

== 20210403213315 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0872s
== 20210403213315 CreateUsers: migrated (0.0873s) =============================

== 20210403213437 AddDeviseToUsers: migrating =================================
-- change_table(:users)
   -> 0.0905s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0088s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0065s
== 20210403213437 AddDeviseToUsers: migrated (0.1069s) ========================

== 20210410151149 CreatePatients: migrating ===================================
-- create_table(:patients)
   -> 0.0915s
-- add_index(:patients, :primary_phone, {:unique=>true})
   -> 0.0058s
-- add_index(:patients, :other_phone)
   -> 0.0047s
-- add_index(:patients, :other_contact)
   -> 0.0044s
-- add_index(:patients, :name)
   -> 0.0058s
-- add_index(:patients, :line)
   -> 0.0042s
-- add_index(:patients, :urgent_flag)
   -> 0.0042s
-- add_index(:patients, :identifier)
   -> 0.0063s
-- add_index(:patients, :pledge_sent)
   -> 0.0062s
== 20210410151149 CreatePatients: migrated (0.1338s) ==========================

== 20210415015227 CreateFulfillment: migrating ================================
-- create_table(:fulfillments)
   -> 0.0539s
-- add_index(:fulfillments, :fulfilled)
   -> 0.0054s
-- add_index(:fulfillments, :audited)
   -> 0.0043s
== 20210415015227 CreateFulfillment: migrated (0.0638s) =======================

== 20210426033002 CreateCalls: migrating ======================================
-- create_table(:calls)
   -> 0.0926s
== 20210426033002 CreateCalls: migrated (0.0927s) =============================

== 20210502050214 CreateCallListEntries: migrating ============================
-- create_table(:call_list_entries)
   -> 0.0622s
-- add_index(:call_list_entries, :line)
   -> 0.0046s
== 20210502050214 CreateCallListEntries: migrated (0.0670s) ===================

== 20210503043154 CreateNotes: migrating ======================================
-- create_table(:notes)
   -> 0.0398s
== 20210503043154 CreateNotes: migrated (0.0399s) =============================

4 Clinic migrated to pg
3 User migrated to pg
39 Patient migrated to pg
39 Fulfillment migrated to pg
141 calls migrated to pg
6 CallListEntry migrated to pg
17 notes migrated to pg
```

**Comment by colinxfleming** [comment]
oh, it looks like you're choking on `CallListEntry`, not `Note`. Can you try clearing out those entries from mongo? `git checkout main && echo "CallListEntry.destroy_all" | rails c` should do the trick

**Comment by lomky** [comment]
That cleaned it up! is this a possible scenario we'll run into in prod?

**Review by lomky — APPROVED** [review]
🗒️ 🎉

**Comment by colinxfleming** [comment]
I think chances are pretty slim; reason is, we wrote a nightly cleanup task to kill off any orphaned call list entries, so that should prevent any scruff from hanging out. My assumption is that if we DO run into that problem, we can address it by running that nightly cleanup task and be good to go.

**Pull request merged**
