### PR TITLE
Upgrade heroku stack

### PR DESCRIPTION
**Pull request by xmunoz**
rule and have completed some work on Case Manager that's ready for review!

(brief, plain english overview of your changes here)

This pull request makes the following changes:
- Makes explicit the require node version, and upgrades that version to 14
- Upgrades the ruby version docker container
- Upgrades yarn to 2.x
- Upgrades some dependencies

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue:
- Upgrade to heroku-20 stack #2285

For reviewer:
- Bring this up locally and click around to make sure everything is gravy

Followup:
- After this is merged, ensure that the sandbox deploy works and looks good.
- Then upgrade the Heroku stack for sandbox
- Verify again that everything looks good
- Promote to prod
- Upgrade the stack for each prod deployment

### CODE REVIEW

**Comment by xmunoz** [comment]
`yarn install` has a lot of issues:

```
warning popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
warning webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack-dev-server > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning webpack-dev-server > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Review by colinxfleming — APPROVED** [review]
I assume the super massive diff is mostly yarn. lgtm - pretty much the same as the last one, yeah?

**Comment by xmunoz** [comment]
Yeah, plus the yarn stuff, which completely changes the format of yarn.lock

**Comment by xmunoz** [comment]
Since this is a big change, I'll wait for @lomky to approve as well before merging and rolling out the new stack.

**Pull request merged**
