### PR TITLE
add research notice to readme

### PR DESCRIPTION
**Pull request by yochannah**
... so contributors are aware this repo is participating in a research project and metrics are being gathered over the next few months.

I rule and have completed some work on Case Manager that's ready for review!

(brief, plain english overview of your changes here)

This pull request makes the following changes:
* (your change here)
* (another change here)
* (etc)

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #X
* Bumps #Y

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

**Review by colinxfleming — APPROVED** [review]
@lomky I saw someone posting about this on the internet and impulsively signed us up to be a data source for it. Short version is that it's an anonymized metric data collection about repo activity for an academic project. I'm good with it but want to make sure you are too!

**Comment by colinxfleming** [comment]
( @yochannah we'll merge after I connect with the other project lead )

**Review by lomky — APPROVED** [review]
SCIENCE! ⚛️ 🧑‍🔬 🎉 
All good by me. I suggest announcing it in the slack channel for full transparency for existing folks who might not be re-reading the README often.

**Comment by yochannah** [comment]
Thanks folks! 🙌

**Pull request merged**
