### PR TITLE
explicit understanding of “timezone hell”

### PR DESCRIPTION
**Pull request by Kevin-Wei**
I rule and have completed some work on Case Manager that's ready for review!

(brief, plain english overview of your changes here)

This pull request makes the following changes:
* Help us understand Audit trails "timezone hell"

(If there are changes to the views, please include a screenshot so we know what to look for!)

Should fix this test so it actually passes late at night EST

### CODE REVIEW

**Comment by Kevin-Wei** [comment]
Will probably fail tommorrow morning.

**Comment by colinxfleming** [comment]
Oh dear

**Comment by colinxfleming** [comment]
(ps nice to see you @Kevin-Wei !)

**Comment by colinxfleming** [comment]
Last night's build seemed to choke on some timezones. Trying the rebuild now to see what happens. 

The danger period is 8pm to midnight EST, yeah? (Or maybe 3 hours right now since we're in EDT I think?)

**Comment by colinxfleming** [comment]
Nah, choking as follows:


```
Failure:
AuditTrailTest::methods#test_0003_should conveniently render what they were before [/home/ubuntu/dcaf_case_management/test/models/audit_trail_test.rb:45]:
--- expected
+++ actual
@@ -1 +1 @@
-["Susie Everyteen", "1112223333", "10/31/2017", "10/29/2017", "D2-3333"]
+["Susie Everyteen", "1112223333", "10/30/2017", "10/28/2017", "D2-3333"]



bin/rails test test/models/audit_trail_test.rb:44

 FAIL["test_0004_should conveniently render what they areTime now", #<Class:0x0000000005659a78>, 54.140606000000844]
 test_0004_should conveniently render what they areTime now#AuditTrailTest::methods (54.15s)
        --- expected
        +++ actual
        @@ -1 +1 @@
        -["Yolo", "1234569999", "11/05/2017", "10/30/2017", "D6-9999"]
        +["Yolo", "1234569999", "11/04/2017", "10/29/2017", "D6-9999"]
        test/models/audit_trail_test.rb:54:in `block (2 levels) in <class:AuditTrailTest>'

F

Failure:
AuditTrailTest::methods#test_0004_should conveniently render what they areTime now [/home/ubuntu/dcaf_case_management/test/models/audit_trail_test.rb:54]:
--- expected
+++ actual
@@ -1 +1 @@
-["Yolo", "1234569999", "11/05/2017", "10/30/2017", "D6-9999"]
+["Yolo", "1234569999", "11/04/2017", "10/29/2017", "D6-9999"]



bin/rails test test/models/audit_trail_test.rb:53
```

**Comment by lomky** [comment]
Done in #1300 to avoid CircleCI throw-ups

**Pull request closed without merging**
