### PR TITLE
Upgrade omniauth-google-oauth2 to 0.8.1, fixes #2141

### LINKED ISSUE #2141: upgrade omniauth
Sqreen currently recommends version 2.0.3.

### PR DESCRIPTION
**Pull request by xmunoz**
I rule and have completed some work on Case Manager that's ready for review!

This pull request makes the following changes:
* upgrade omniauth-google-oauth2
* upgrade devise
* explicitly add new dependency: [omniauth-rails_csrf_protection](https://github.com/cookpad/omniauth-rails_csrf_protection) (reason: https://github.com/omniauth/omniauth/wiki/Upgrading-to-2.0#rails)

It relates to the following issue #s: 
* Fixes #2141 

For reviewer:
* When this is ready, I will remove the `WIP` prefix from the PR title and assign reviewers.
* I will create user accounts for the reviewers on sandbox.
* I will deploy this branch to sandbox, temporarily hijacking the normal release flow for testing purposes.
* Reviewers will try to sign in with Google to confirm that the change works.

### CODE REVIEW

**Comment by xmunoz** [comment]
Current status: Login with Google test fails in this way:

imagen

Also, the current PR is still not great, because it requires pointing to the head of master for the `devise` package.

**Comment by xmunoz** [comment]
Hmm, now that I'm remembering how we on-boarded the last fund, I don't think it will be possible to test this on sandbox until #2120 is closed. @colinxfleming @lomky can you confirm that this is a blocker?

**Comment by colinxfleming** [comment]
hm, these are the endpoints that the sandbox creds are auth'd on:

image

so if you're grabbing the googly creds from sandbox, I would have expected that to not complain about `forbidden`. I'll try to recreate this tmw.

I'm not sure #2120 matters -- I thnk that's more for adding more authorized domains, and I don't _think_ we need that for this, right?

**Comment by xmunoz** [comment]
My plan was to deploy to sandbox for testing the upgrade; I don't think telling Google to redirect to `localhost` will work.

Also, where did you get that screenshot from? AFAIK we removed the Sandbox Google OAuth creds when onboarding the latest fund because we ran out of domains (prompting you to go through app verification in #2120).

I think we are done with verification though, because I was able to add back Sandbox to the list of OAuth clients just now, and test that logging in with Google works.

**Comment by xmunoz** [comment]
This is the failing test:
test_0001_can sign in with Google Auth Account - GoogleSSOTest::access top page

Why do we also need to upgrade devise? This is the thread: https://github.com/heartcombo/devise/pull/5327

In the mean time, there is a failing test, and it's unclear whether this is something devise still needs to fix for the new omniauth version, something broken in the test, or something broken in our app since the upgrade.

This can be tested by deploying this PR to Sandbox and seeing if "Login with Google" still works. Even if it does though, I would feel super uncomfortable merging a PR that essential points to HEAD of devise. That maintainer hasn't released a new version yet with the required fixes. In my opinion, the best thing to do is wait.

**Comment by colinxfleming** [comment]
Definitely agree we should keep our powder dry until a new devise version comes out! I'll adjust issue title accordingly.

**Review by colinxfleming — APPROVED** [review]
lovely! I checked the devise release notes and this matches what I'd expect out of that. fire when ready!

**Pull request merged**
